experiment_name: "hybrid_qcnn_fashion_exp"

dataset:
  name: fashion_mnist
  binary_classes: [3, 8]  # Ex: Pull-over vs Sandal
  in_channels: 1

training:
  batch_size: 64
  epochs: 100                # Nombre d'époques pour l'entraînement du feature extractor
  learning_rate: 0.0005      # LR initial pour Adam
  kfold: 3                   # Nombre de splits pour KFold cross-validation
  early_stopping: 50          # Patience d'early stopping
  warmup_epochs: 5     # <--- Ajout !
  scheduler: "StepLR"          # Options: null, StepLR, MultiStepLR, CosineAnnealingLR
  scheduler_params:
    step_size: 5              # Applicable à StepLR
    gamma: 0.5                 # Facteur de réduction du LR

model:
  input_size: 784  # Fashion-MNIST images 28x28 aplaties
  quantum:
    n_qubits: 4
    n_layers: 1
    backend: "default.qubit"

checkpoint:
  save_dir: "checkpoints"
  subdir: "hybrid_qcnn_fashion_mnist_experiment"

quantum:
  n_qubits: 4
  layers: 2
  backend: "lightning.qubit"